# Generated by Django 3.1.3 on 2020-11-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlineclassroom',
            old_name='start_by',
            new_name='started_by',
        ),
        migrations.AddField(
            model_name='students',
            name='test_field',
            field=models.IntegerField(default=0),
        ),
    ]
