# Generated by Django 3.1.3 on 2020-11-29 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_management_app', '0002_auto_20201128_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffs',
            old_name='fmc_token',
            new_name='fcm_token',
        ),
    ]
